version: "3.8"
services:
  kraken-scheduler:
    image: kraken-scheduler:latest
    volumes:
    - ./config:/config
    entrypoint: >
      kraken-scheduler-linux-amd64
        --config ${CONFIG:-"/config/config.json"}
        --telegram-credentials ${TELEGRAM_CREDENTIALS:-""}
        --email-credentials ${EMAIL_CREDENTIALS:-""}
        --key ${KEY?"KEY variable is required"}
        --secret ${SECRET?"SECRET variable is required"}
        --live
    restart: on-failure